### ISSUE TITLE
crash after last update

### ISSUE THREAD

**Issue by infernvs** [hdnpt/geartrack-website#22]
Bugsnag:  TypeError: cb is not a function
    at Request.<anonymous> (/home/cerbervs/geartrack-website/node_modules/geartrack/src/correosOldTracker.js:33:13)
    at Request._callback (/home/cerbervs/geartrack-website/node_modules/lodash/lodash.js:10067:25)
    at Request.requestRetryReply [as reply] (/home/cerbervs/geartrack-website/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/home/cerbervs/geartrack-website/node_modules/requestretry/index.js:133:10)
    at Request.self.callback (/home/cerbervs/geartrack-website/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/home/cerbervs/geartrack-website/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/home/cerbervs/geartrack-website/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geartrack-website@1.0.2 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the geartrack-website@1.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cerbervs/.npm/_logs/2017-05-22T10_06_46_305Z-debug.log

**Comment by iamfreee** [comment]
Hi, 

Try to update the geartrack package: npm install. 
Check the package.json to see if the version is correct, geartrack is at version 2..

**Comment by infernvs** [comment]
Hello again, it's working now, for some reason wasn't doing anything on npm install but it's working now, tnks.
